<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\File;

class CleanTemporaryFiles extends Command{
    protected $signature = 'clean:temp-files';
    protected $description = 'Clean up temporary files generated by Laravel Excel';

    public function __construct()
    {
        parent::__construct();
    }

    public function handle()
    {
        $tempPath = storage_path('framework/laravel-excel');
        $files = File::files($tempPath);

        foreach ($files as $file) {
            if ($file->getExtension() === 'tmp') {
                File::delete($file->getPathname());
            }
        }

        $this->info('Temporary files cleaned up successfully.');
    }
}